# Generated by Django 5.0.6 on 2024-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments_link_payments_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ID сессии'),
        ),
    ]
